version: 2

sources:
  - name: jaffle_shop
    database: demo_db
    schema: raw_jaffle_shop
    tables:
      - name: orders
        config: 
          freshness:
            warn_after:
              count: 1
              period: day
            error_after:
              count: 50
              period: day
          loaded_at_field: _etc_loaded_at
      - name: customers

  - name: stripe 
    database: demo_db
    schema: raw_stripe 
    tables:
      - name: payment